/**
 * Fetches Stripe Prices for each slot env var and writes a typed catalog file
 * at apps/web/src/lib/config/funnels.generated.ts. Runs as `prebuild` and
 * `predev:web`. Stripe is the source of truth for price + name + r2_key
 * (Product metadata); display copy stays hardcoded in funnels.ts.
 *
 * Modes:
 *   --mode=build (default): hard-fail on any error or unset STRIPE_SECRET_KEY
 *   --mode=dev:             tolerate failures; reuse previous file if present;
 *                           if absent, write an empty catalog (zero slots).
 *
 * To make a new product visible in the funnel:
 *   1. Create a Product + Price in Stripe Dashboard.
 *   2. Set Product metadata `r2_key` to the object key (e.g. "starter-funnel/core/starter-playbook.pdf").
 *   3. Add the Price ID to the matching STRIPE_TEST_PRICE_* / STRIPE_LIVE_PRICE_* env var.
 *   4. Redeploy (or run `pnpm sync:stripe` locally).
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Stripe from "stripe";

import { getStripeMode, resolveStripeEnv } from "../src/lib/server/stripe-env";

const SLOTS = ["CORE", "ORDER_BUMP_1", "ORDER_BUMP_2", "OTO", "DOWNSELL"] as const;
type Slot = (typeof SLOTS)[number];

const SLOT_TO_CANONICAL: Record<Slot, string> = {
  CORE: "STRIPE_PRICE_CORE",
  ORDER_BUMP_1: "STRIPE_PRICE_ORDER_BUMP_1",
  ORDER_BUMP_2: "STRIPE_PRICE_ORDER_BUMP_2",
  OTO: "STRIPE_PRICE_OTO",
  DOWNSELL: "STRIPE_PRICE_DOWNSELL"
};

type GeneratedSlot = {
  priceId: string;
  productId: string;
  name: string;
  currency: string;
  unitAmount: number;
  r2Key: string | null;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, "../src/lib/config/funnels.generated.ts");

const mode = (process.argv.find((a) => a.startsWith("--mode="))?.split("=")[1] ?? "build") as
  | "build"
  | "dev";
const placeholderPattern = /(placeholder|changeme|replace|example|dummy|local_placeholder)/i;

function exitFatal(message: string): never {
  console.error(`[sync-stripe] ${message}`);
  process.exit(1);
}

function warn(message: string) {
  console.warn(`[sync-stripe] ${message}`);
}

function info(message: string) {
  console.log(`[sync-stripe] ${message}`);
}

async function fetchSlot(stripe: Stripe, slot: Slot, priceId: string): Promise<GeneratedSlot> {
  const price = await stripe.prices.retrieve(priceId, { expand: ["product"] });
  if (!price.active) {
    throw new Error(`Price ${priceId} (${slot}) is archived in Stripe`);
  }
  if (price.unit_amount == null) {
    throw new Error(`Price ${priceId} (${slot}) has no unit_amount (tiered/usage prices unsupported)`);
  }
  const product = price.product;
  if (typeof product === "string" || !product || product.deleted) {
    throw new Error(`Price ${priceId} (${slot}) has no usable Product attached`);
  }

  const r2Key = (product.metadata?.r2_key ?? "").trim() || null;

  return {
    priceId: price.id,
    productId: product.id,
    name: product.name,
    currency: price.currency.toLowerCase(),
    unitAmount: price.unit_amount,
    r2Key
  };
}

function renderFile(slots: Partial<Record<Slot, GeneratedSlot>>): string {
  const generatedAt = new Date().toISOString();
  const body = JSON.stringify(slots, null, 2);

  return `/* eslint-disable */
// AUTO-GENERATED by apps/web/scripts/sync-stripe-products.ts. DO NOT EDIT.
// Source: Stripe Prices + Product metadata. Re-run \`pnpm sync:stripe\`.
// Generated at: ${generatedAt}

export type StripeSlot = "CORE" | "ORDER_BUMP_1" | "ORDER_BUMP_2" | "OTO" | "DOWNSELL";

export type GeneratedSlot = {
  priceId: string;
  productId: string;
  name: string;
  currency: string;
  unitAmount: number;
  r2Key: string | null;
};

export const stripeSlots: Partial<Record<StripeSlot, GeneratedSlot>> = ${body};
`;
}

function readPreviouslyGenerated(): string | null {
  if (!existsSync(OUTPUT_PATH)) return null;
  try {
    return readFileSync(OUTPUT_PATH, "utf8");
  } catch {
    return null;
  }
}

async function main() {
  const stripeMode = getStripeMode(process.env);
  const stripeEnv = resolveStripeEnv(process.env);
  info(`Stripe mode: ${stripeMode} (raw STRIPE_MODE="${process.env.STRIPE_MODE ?? "<unset>"}")`);
  info(`Visible STRIPE_* env keys: ${Object.keys(process.env).filter(k => k.startsWith("STRIPE_") || k === "PUBLIC_STRIPE_PUBLISHABLE_KEY").sort().join(", ") || "<none>"}`);

  const secretKey = placeholderPattern.test(stripeEnv.STRIPE_SECRET_KEY ?? "")
    ? ""
    : stripeEnv.STRIPE_SECRET_KEY;
  const apiVersion = process.env.STRIPE_API_VERSION ?? "2026-02-25.clover";

  const requestedSlots = SLOTS.map((slot) => {
    const priceId = stripeEnv[SLOT_TO_CANONICAL[slot]];
    return priceId ? { slot, priceId } : null;
  }).filter((entry): entry is { slot: Slot; priceId: string } => Boolean(entry));

  if (!secretKey) {
    if (mode === "build" && readPreviouslyGenerated()) {
      warn(`STRIPE_${stripeMode.toUpperCase()}_SECRET_KEY is missing or still a placeholder; reusing committed starter catalog.`);
      return;
    }
    if (mode === "build") {
      exitFatal(`STRIPE_${stripeMode.toUpperCase()}_SECRET_KEY is required in build mode (STRIPE_MODE=${stripeMode}).`);
    }
    warn(`STRIPE_${stripeMode.toUpperCase()}_SECRET_KEY missing in dev mode.`);
    if (readPreviouslyGenerated()) {
      info("Reusing previously generated funnels.generated.ts.");
      return;
    }
    info("Writing empty catalog (no slots).");
    writeFileSync(OUTPUT_PATH, renderFile({}));
    return;
  }

  if (requestedSlots.length === 0) {
    if (mode === "build") {
      exitFatal(
        `No STRIPE_${stripeMode.toUpperCase()}_PRICE_* env vars set. At minimum STRIPE_${stripeMode.toUpperCase()}_PRICE_CORE is required to ship a checkout.`
      );
    }
    warn(`No STRIPE_${stripeMode.toUpperCase()}_PRICE_* env vars set. Writing empty catalog.`);
    writeFileSync(OUTPUT_PATH, renderFile({}));
    return;
  }

  const stripe = new Stripe(secretKey, {
    apiVersion: apiVersion as never,
    appInfo: { name: "agentic-funnel-sync", version: "0.1.0" }
  });

  info(`Fetching ${requestedSlots.length} slot(s) from Stripe…`);
  const results = await Promise.allSettled(
    requestedSlots.map(async ({ slot, priceId }) => ({ slot, data: await fetchSlot(stripe, slot, priceId) }))
  );

  const slots: Partial<Record<Slot, GeneratedSlot>> = {};
  const failures: Array<{ slot: Slot; error: unknown }> = [];

  for (let i = 0; i < results.length; i++) {
    const result = results[i];
    const { slot } = requestedSlots[i];
    if (result.status === "fulfilled") {
      slots[slot] = result.value.data;
      const data = result.value.data;
      const major = (data.unitAmount / 100).toFixed(2);
      info(`  ${slot.padEnd(13)} ${data.priceId} → "${data.name}" ${major} ${data.currency}${data.r2Key ? ` r2_key=${data.r2Key}` : " (no r2_key)"}`);
    } else {
      failures.push({ slot, error: result.reason });
      warn(`  ${slot.padEnd(13)} FAILED: ${(result.reason as Error)?.message ?? result.reason}`);
    }
  }

  if (failures.length > 0 && mode === "build") {
    exitFatal(`${failures.length} slot(s) failed to resolve. Refusing to ship.`);
  }

  if (failures.length > 0 && mode === "dev") {
    if (Object.keys(slots).length === 0 && readPreviouslyGenerated()) {
      warn("All Stripe fetches failed in dev mode; reusing previously generated file.");
      return;
    }
    warn("Some slots failed; writing partial catalog (dev mode).");
  }

  writeFileSync(OUTPUT_PATH, renderFile(slots));
  info(`Wrote ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error("[sync-stripe] Fatal error:", err);
  process.exit(1);
});
